services:
  - type: web
    name: nest-api
    env: node
    plan: free
    buildCommand: npm run build
    startCommand: npm run start:prod
    envVars:
      - key: NODE_VERSION
        value: 18.20.2
    autoDeploy: true
    branch: main
